/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Registration;

import Classes.Helper;
import Classes.JDBC;
import Classes.Validation;
import GUI.EXceptionAndToast.Toast;
import com.toedter.calendar.JDateChooser;
import datechooser.beans.DateChooserCombo;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hasitha Udara
 */
public class UserRegistration extends javax.swing.JFrame {

    private Helper helper = new Helper();
    private JDBC db = new JDBC();
    private Validation v = new Validation();
    TableColumn myTableColumn0;
    TableColumn myTableColumn1;
    private JFrame parent;

    /**
     * Creates new form UserRegistration
     */
    public UserRegistration() {
        initComponents();
//        InitialDataLoader();
//        myTableColumn0 = jTable2.getColumnModel().getColumn(0);
//        helper.hideColumn(jTable2, myTableColumn0);
//        helper.setDefaultDate(jDateChooser1);
//        idText.setVisible(false);

    }

    public UserRegistration(JFrame parent) {
        initComponents();
        InitialDataLoader();
        myTableColumn0 = jTable2.getColumnModel().getColumn(0);
        helper.hideColumn(jTable2, myTableColumn0);
        helper.setDefaultDate(jDateChooser1);
        idText.setVisible(false);
        this.parent = parent;
        this.parent.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        DOB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ssss = new javax.swing.JPanel();
        MobileNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HomeTel = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AddressLine0 = new javax.swing.JTextField();
        AddressLine1 = new javax.swing.JTextField();
        AddressLine2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        userNameText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        UserType = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        UserRegistrationCheckBox = new javax.swing.JCheckBox();
        ReseavasionCheckBox = new javax.swing.JCheckBox();
        ResturantCheckBox = new javax.swing.JCheckBox();
        ReportsCheckBoxs = new javax.swing.JCheckBox();
        FeedbackCheckBox = new javax.swing.JCheckBox();
        MenueCheckBox = new javax.swing.JCheckBox();
        loadSelected = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        idText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User Registration");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration Form for User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 12), java.awt.Color.black)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "User Type", "Email", "Mobile no", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Common Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), java.awt.Color.black)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel3.setText("Last  Name :");

        FirstName.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        FirstName.setName("First Name"); // NOI18N
        FirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FirstNameKeyTyped(evt);
            }
        });

        LastName.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        LastName.setName("Last Name"); // NOI18N
        LastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LastNameKeyTyped(evt);
            }
        });

        DOB.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        DOB.setText("Date of Birth :");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel8.setText("NIC Number :");

        Nic.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        Nic.setName("NIC"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel9.setText("Gender :");

        gender.add(Male);
        Male.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        Male.setLabel("male");
        Male.setName("Male"); // NOI18N

        gender.add(Female);
        Female.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        Female.setText("Female");
        Female.setName("Female"); // NOI18N

        jDateChooser1.setDateFormatString("dd-MMM-yyyy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DOB)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Male)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Female))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(73, 73, 73)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastName, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Nic, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Male)
                        .addComponent(Female))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("By Name");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jRadioButton2.setText("By NIC");
        jRadioButton2.setContentAreaFilled(false);

        jTextField4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel22.setText("Select User :");

        ssss.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), java.awt.Color.black)); // NOI18N

        MobileNo.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        MobileNo.setName("Mobile "); // NOI18N
        MobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MobileNoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel6.setText("Mobile No :");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel7.setText("Home No :");

        HomeTel.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        HomeTel.setName("Home"); // NOI18N
        HomeTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HomeTelKeyTyped(evt);
            }
        });

        Email.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        Email.setName("Email"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel4.setText("Email Address :");

        javax.swing.GroupLayout ssssLayout = new javax.swing.GroupLayout(ssss);
        ssss.setLayout(ssssLayout);
        ssssLayout.setHorizontalGroup(
            ssssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ssssLayout.createSequentialGroup()
                .addGroup(ssssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(ssssLayout.createSequentialGroup()
                .addGroup(ssssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeTel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MobileNo))
                .addGap(22, 22, 22))
        );
        ssssLayout.setVerticalGroup(
            ssssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ssssLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(HomeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), java.awt.Color.black)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel10.setText("Address Number :");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel11.setText("Address Line 01 :");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel12.setText("Address Line 02 :");

        AddressLine0.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        AddressLine0.setName("Address No"); // NOI18N

        AddressLine1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        AddressLine1.setName("Address Line 1"); // NOI18N

        AddressLine2.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        AddressLine2.setName("Address Line 2"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddressLine0, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressLine0, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddressLine1)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setText("Save User");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton3.setText("Update User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton4.setText("Search");

        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Login Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), java.awt.Color.black)); // NOI18N

        userNameText.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        userNameText.setName("User Name"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel13.setText("User Name :");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel14.setText("Password :");

        PasswordText.setName("Password"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel15.setText("Confirm Password :");

        jPasswordField2.setName("ConfirmPassword"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(PasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(userNameText)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton6.setText("Clear Fields");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Access Privileges", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), java.awt.Color.black)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel17.setText("User Type :");

        UserType.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        UserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Type --", "Admin", "Receptionist", "Resturent Manager" }));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Privilages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 10), java.awt.Color.black)); // NOI18N

        UserRegistrationCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        UserRegistrationCheckBox.setText("User Registration");
        UserRegistrationCheckBox.setContentAreaFilled(false);
        UserRegistrationCheckBox.setName("a"); // NOI18N

        ReseavasionCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        ReseavasionCheckBox.setText("Reservations");
        ReseavasionCheckBox.setContentAreaFilled(false);
        ReseavasionCheckBox.setName("c"); // NOI18N

        ResturantCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        ResturantCheckBox.setText("Restaurent");
        ResturantCheckBox.setContentAreaFilled(false);
        ResturantCheckBox.setName("e"); // NOI18N

        ReportsCheckBoxs.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        ReportsCheckBoxs.setText("Reports");
        ReportsCheckBoxs.setContentAreaFilled(false);
        ReportsCheckBoxs.setName("b"); // NOI18N

        FeedbackCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        FeedbackCheckBox.setText("Feed Back");
        FeedbackCheckBox.setContentAreaFilled(false);
        FeedbackCheckBox.setName("d"); // NOI18N

        MenueCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        MenueCheckBox.setText("Menu");
        MenueCheckBox.setContentAreaFilled(false);
        MenueCheckBox.setName("f"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReseavasionCheckBox)
                            .addComponent(ResturantCheckBox))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FeedbackCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(MenueCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(UserRegistrationCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReportsCheckBoxs)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserRegistrationCheckBox)
                    .addComponent(ReportsCheckBoxs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReseavasionCheckBox)
                    .addComponent(FeedbackCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenueCheckBox)
                    .addComponent(ResturantCheckBox))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(UserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        loadSelected.setText("Load Selected");
        loadSelected.setActionCommand("Edit");
        loadSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSelectedActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Remove");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ssss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loadSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(loadSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );

        idText.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        JTextField[] FieldSet = {
            Nic,
            Email,
            FirstName,
            LastName,
            AddressLine0,
            AddressLine1,
            AddressLine2,
            MobileNo,
            HomeTel

        };

        JPasswordField[] FieldSetpass = {
            PasswordText,
            jPasswordField2

        };

        v.emptyTextfield(FieldSet);
        v.emptyPasswordfield(FieldSetpass);
        v.comboBoxChecker("UserType", UserType);
        v.checkBoxChecker("Previlages", UserRegistrationCheckBox, FeedbackCheckBox, MenueCheckBox, ReportsCheckBoxs, ReseavasionCheckBox, ResturantCheckBox);
        v.radioButtonChecker("Gender", Male, Female);
        v.Emailvalidate(Email.getText());
        v.validationNIC(Nic.getText());
        v.validationPhone(MobileNo.getText(), "Mobile");
        v.validationPhone(HomeTel.getText(), "home");
        v.passwordMissMatchChecker(PasswordText, jPasswordField2);
        boolean isValidated = v.validateForm(this);

        if (isValidated) {
            String Gender = null;
            Gender = (Male.isSelected() == true) ? "Male" : (Female.isSelected() == true) ? "Female" : "Non";

            String Privilages = "";

            Component[] checks = jPanel8.getComponents();

            for (Component check : checks) {

                if (((JCheckBox) check).isSelected() == true) {

                    Privilages += ((JCheckBox) check).getName();

                }

            }

            char[] array = Privilages.toCharArray();

            Arrays.sort(array);
            Privilages = new String(array);
            String today = new SimpleDateFormat("dd-MMM-yyyy").format(new Date());


            /*for user*/
            String[] FieldSet0 = {
                userNameText.getText(),
                new String(PasswordText.getPassword()), UserType.getSelectedItem().toString()};

            /*for registration tbl*/
            String[] FieldSet2 = {};

            /* 
            System.out.println("DATE "+ dateChooserCombo1.getText());
            System.out.println("Date 2"+today);*/
            String HashedPassword = Helper.Hashing(new String(PasswordText.getPassword()));

           
            String Query2 = "'" + userNameText.getText() + "','" + HashedPassword + "','" + UserType.getSelectedItem().toString() + "'";
            String logingID = null;
            try {
                db.InsertDataToDB("username,password,Type", Query2, "login");

                ResultSet rs = db.getData("SELECT idlogin FROM login ORDER BY  idlogin DESC limit 1;");
                while (rs.next()) {

                    logingID = rs.getString(1);

                }
                String selectedDate = new SimpleDateFormat("dd-MMM-yyyy").format(jDateChooser1.getDate());
                String[] FieldSet1 = {
                    Nic.getText(),
                    Email.getText(),
                    FirstName.getText(),
                    LastName.getText(),
                    selectedDate,
                    Gender,
                    AddressLine0.getText(),
                    AddressLine1.getText(),
                    AddressLine2.getText(),
                    today,
                    MobileNo.getText(),
                    HomeTel.getText(),
                    "Active",
                    Privilages,
                    logingID
                };

                String query3 = helper.querySetter1(FieldSet1);
                db.InsertDataToDB("nicno,email,fname,lname,dob,gender,addressno,addr_line1,addr_line2,registerd_date,mobile_no,home_no,status,privilages,login_idlogin", query3, "user_registration");
                //JDBC.con().close();
            } catch (Exception e) {

//                System.out.println("Execption" + e);
                e.printStackTrace();
            }

            Toast succesfulMessage = new Toast("You have Succsessfull addesd User to the System.", 1, this);
            succesfulMessage.setVisible(true);

            helper.clearTextFields(jPanel3, ssss, jPanel5, jPanel6, jPanel8, jPanel7);
            helper.setDefaultDate(jDateChooser1);

            helper.clearTable(jTable2);
            helper.showColumn(jTable2, myTableColumn0);
            ResultSet Rs = db.getData("SELECT user.iduser_registration,concat(user.fname,\" \",user.lname) AS Name,login.Type,user.email,user.mobile_no,user.status FROM \n"
                    + "hotelres.login as login ,hotelres.user_registration as user WHERE  login.idlogin = user.login_idlogin  AND status ='Active'");
            db.addToTable(jTable2, Rs);
            helper.hideColumn(jTable2, myTableColumn0);
            
            
            int index=jTable2.getRowCount()-1;
            
            helper.selectlastAddedUpdatedRecord(jTable2, index);

        }


    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        helper.clearTable(jTable2);
        helper.showColumn(jTable2, myTableColumn0);
        ResultSet Rs = db.getData("SELECT user.iduser_registration,concat(user.fname,\" \",user.lname) AS Name,login.Type,user.email,user.mobile_no,user.status FROM \n"
                + "hotelres.login as login ,hotelres.user_registration as user WHERE  login.idlogin = user.login_idlogin  AND status ='Active'");
        db.addToTable(jTable2, Rs);
        helper.hideColumn(jTable2, myTableColumn0);


    }//GEN-LAST:event_jButton5ActionPerformed

    private void loadSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSelectedActionPerformed

        int[] Rows = jTable2.getSelectedRows();

        if (Rows.length == 0) {
            Toast message = new Toast("No Any Row Selected For Edit and update", 1, this);
            message.setVisible(true);

        } else if (Rows.length > 1) {

            Toast message = new Toast("cant Ubpade Multiple Rows at Same Rime", 1, this);
            message.setVisible(true);

        } else {

            String id = jTable2.getModel().getValueAt(Rows[0], 0).toString();
            //
            String query = "SELECT login_idlogin FROM user_registration WHERE iduser_registration='" + id + "'";
            ResultSet Rs = db.getData(query);
            String idtable2 = helper.getSinglevalue(Rs, 1);
            helper.setTempValue(idtable2);

            //System.out.println("lalalala "+id);
            //helper.getSelectedRows();
            String Query = "SELECT "
                    + "user.iduser_registration,"
                    + "user.fname,"
                    + "user.lname,"
                    + "user.nicno,"
                    + "user.mobile_no,"
                    + "user.home_no,"
                    + "user.email,"
                    + "user.addressno,"
                    + "user.addr_line1,"
                    + "user.addr_line2,"
                    + "login.username,"
                    + "user.dob,"
                    + "user.gender,"
                    + "user.privilages,"
                    + "login.Type "
                    + "FROM "
                    + "login as login ,user_registration as user WHERE  login.idlogin = user.login_idlogin  AND status ='Active' AND user.iduser_registration='" + id + "'";

            System.out.println(Query);
            Rs = db.getData(Query);
            helper.spliitDataSet(Rs, 11, 1, 1, 1, 1);
            JDBC.TerminateConnection();

            JTextField[] fields = {
                idText,
                FirstName,
                LastName,
                Nic,
                MobileNo,
                HomeTel,
                Email,
                AddressLine0,
                AddressLine1,
                AddressLine2,
                userNameText

            };

            helper.tofields(fields);

            JDateChooser[] datepickers = {
                jDateChooser1
            };

            helper.toDateChooser(datepickers);

            JRadioButton[] radioButtons = {
                Male,
                Female

            };

            helper.toRadio("Male", "Female", radioButtons, 0);

            JComboBox[] comboset
                    = {
                        UserType

                    };

            helper.toCombo(comboset, 0);

            JCheckBox[] checks
                    = {
                        UserRegistrationCheckBox,
                        ReportsCheckBoxs,
                        ReseavasionCheckBox,
                        FeedbackCheckBox,
                        MenueCheckBox,
                        ResturantCheckBox

                    };

            helper.toCheckBoxMultipleValue(checks, 0);

        }


    }//GEN-LAST:event_loadSelectedActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        int[] Rows = jTable2.getSelectedRows();

        if (Rows.length == 0) {
            Toast message = new Toast("No Any Row Selected For Edit and update", 1, this);
            message.setVisible(true);

        } else {

            String Q1 = "status= '" + "Inactive" + "'";
            String Q2 = "iduser_registration =";

            for (int Row : Rows) {

                String idSet = jTable2.getModel().getValueAt(Row, 0).toString();
                Q2 += "'" + idSet + "'";
                db.UpdateDataBaseTable("user_registration", Q1, Q2);
                Q2 = "iduser_registration =";

            }

        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int[] Rows = jTable2.getSelectedRows();

        if (Rows.length == 0) {
            Toast message = new Toast("No Any Row Selected For Edit and update", 1, this);
            message.setVisible(true);

        } else if (Rows.length > 1) {

            Toast message = new Toast("cant Ubpade Multiple Rows at Same Rime", 1, this);
            message.setVisible(true);

        } else {

            JTextField[] FieldSet = {
                Nic,
                Email,
                FirstName,
                LastName,
                AddressLine0,
                AddressLine1,
                AddressLine2,
                MobileNo,
                HomeTel,
                userNameText

            };

            JPasswordField[] FieldSet2 = {
                PasswordText,
                jPasswordField2

            };

            v.emptyTextfield(FieldSet);
            v.emptyPasswordfield(FieldSet2);
            v.comboBoxChecker("UserType", UserType);
            v.checkBoxChecker("Previlages", UserRegistrationCheckBox, FeedbackCheckBox, MenueCheckBox, ReportsCheckBoxs, ReseavasionCheckBox, ResturantCheckBox);
            v.radioButtonChecker("Gender", Male, Female);
            v.Emailvalidate(Email.getText());
            v.validationNIC(Nic.getText());
            v.validationPhone(MobileNo.getText(), "Mobile");
            v.validationPhone(HomeTel.getText(), "home");
            v.passwordMissMatchChecker(PasswordText, jPasswordField2);
            boolean isValidated = v.validateForm(this);

            if (isValidated) {

                String idTable2 = helper.getTempValue();
                helper.removeTempValue();

                String HashedPassword = Helper.Hashing(new String(PasswordText.getPassword()));

                String q1 = "username = '" + userNameText.getText() + "' ,";
                q1 += "password = '" + HashedPassword + "' ,";
                q1 += "Type = '" + UserType.getSelectedItem().toString() + "'";

                String q2 = "idlogin ='" + idTable2 + "'";

                db.UpdateDataBaseTable("login", q1, q2);

                String Gender = null;
                Gender = (Male.isSelected() == true) ? "Male" : (Female.isSelected() == true) ? "Female" : "Non";

                String Privilages = "";

                Component[] checks = jPanel8.getComponents();

                for (Component check : checks) {

                    if (((JCheckBox) check).isSelected() == true) {

                        Privilages += ((JCheckBox) check).getName();

                    }

                }

                char[] array = Privilages.toCharArray();

                Arrays.sort(array);
                Privilages = new String(array);
                String today = new SimpleDateFormat("dd-MMM-yyyy").format(new Date());
                String dob = helper.getDateFromJDateChooser(jDateChooser1);

                //,,,,,,,,,,,login_idlogin
                String Q1 = "nicno = '" + Nic.getText() + "' ,";
                Q1 += "email = '" + Email.getText() + "' ,";
                Q1 += "fname = '" + FirstName.getText() + "' ,";
                Q1 += "lname = '" + LastName.getText() + "' ,";
                Q1 += "dob = '" + dob + "' ,";
                Q1 += "gender = '" + Gender + "' ,";
                Q1 += "addressno = '" + AddressLine0.getText() + "' ,";
                Q1 += "addr_line1 = '" + AddressLine1.getText() + "' ,";
                Q1 += "addr_line2 = '" + AddressLine2.getText() + "' ,";
                Q1 += "registerd_date= '" + today + "' ,";
                Q1 += "mobile_no= '" + MobileNo.getText() + "' ,";
                Q1 += "home_no= '" + HomeTel.getText() + "' ,";
                Q1 += "status= '" + "Active" + "' ,";
                Q1 += "privilages= '" + Privilages + "'";

                String Q2 = "iduser_registration ='" + idText.getText() + "'";

                db.UpdateDataBaseTable("user_registration", Q1, Q2);

                Toast succesfulMessage = new Toast("You have Succsessfull Updated User to the System.", 1, this);
                succesfulMessage.setVisible(true);

                helper.clearTextFields(jPanel3, ssss, jPanel5, jPanel6, jPanel8, jPanel7);
                helper.setDefaultDate(jDateChooser1);

                helper.clearTable(jTable2);
                helper.showColumn(jTable2, myTableColumn0);
                ResultSet Rs = db.getData("SELECT user.iduser_registration,concat(user.fname,\" \",user.lname) AS Name,login.Type,user.email,user.mobile_no,user.status FROM \n"
                        + "hotelres.login as login ,hotelres.user_registration as user WHERE  login.idlogin = user.login_idlogin  AND status ='Active'");
                db.addToTable(jTable2, Rs);
                helper.hideColumn(jTable2, myTableColumn0);
                
                 int index=Rows[0];
                 helper.selectlastAddedUpdatedRecord(jTable2, index);

            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        //clear TextFikleds//
        helper.clearTextFields(jPanel3, ssss, jPanel5, jPanel6, jPanel8, jPanel7);
        helper.setDefaultDate(jDateChooser1);
        //need to clear radio and check reset combo


    }//GEN-LAST:event_jButton6ActionPerformed

    private void FirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameKeyTyped
        Validation.numberChecker(evt);
    }//GEN-LAST:event_FirstNameKeyTyped

    private void LastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameKeyTyped
        Validation.numberChecker(evt);
    }//GEN-LAST:event_LastNameKeyTyped

    private void MobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobileNoKeyTyped
        Validation.CharacterChecker(evt);
    }//GEN-LAST:event_MobileNoKeyTyped

    private void HomeTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HomeTelKeyTyped
        Validation.CharacterChecker(evt);
    }//GEN-LAST:event_HomeTelKeyTyped

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed


    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressLine0;
    private javax.swing.JTextField AddressLine1;
    private javax.swing.JTextField AddressLine2;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField Email;
    private javax.swing.JCheckBox FeedbackCheckBox;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField HomeTel;
    private javax.swing.JTextField LastName;
    private javax.swing.JRadioButton Male;
    private javax.swing.JCheckBox MenueCheckBox;
    private javax.swing.JTextField MobileNo;
    private javax.swing.JTextField Nic;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JCheckBox ReportsCheckBoxs;
    private javax.swing.JCheckBox ReseavasionCheckBox;
    private javax.swing.JCheckBox ResturantCheckBox;
    private javax.swing.JCheckBox UserRegistrationCheckBox;
    private javax.swing.JComboBox UserType;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton loadSelected;
    private javax.swing.JPanel ssss;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables

    private void InitialDataLoader() {

        /*
        SELECT user.iduser_registration,concat(user.fname," ",user.lname) AS Name,login.Type,user.email,user.mobile_no,user.status FROM 
hotelres.login as login ,hotelres.user_registration as user
        
         */
        ResultSet Rs = db.getData("SELECT user.iduser_registration,concat(user.fname,\" \",user.lname) AS Name,login.Type,user.email,user.mobile_no,user.status FROM hotelres.login as login ,hotelres.user_registration as user WHERE  login.idlogin = user.login_idlogin  AND status ='Active'");
        // helper.addToTable(jTable2, Rs);
        db.addToTable(jTable2, Rs);

    }
}
