/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JViewport;

/**
 *
 * @author Ice
 */
public class MenueCustomizer extends javax.swing.JFrame {

    /**
     * Creates new form MenueCustomizer
     */
    
    GroupLayout backGroundLayout;
    ParallelGroup pg2;
    private int num=0;
    JPanel backGround;
   
    SequentialGroup vsq1;
    
    public MenueCustomizer() {
        initComponents();
        initComponentCustom();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(90, 90, 90)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        String section ="SECTION "+Integer.toString(num);
        JLabel jl=new JLabel(section);
        jl.setName("fuck");
        
        
        
        
        SequentialGroup sq4 = backGroundLayout.createSequentialGroup();
        sq4.addContainerGap();
        sq4.addComponent(jl, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE);
        
        
        vsq1.addGap(50, 50, 50);
        vsq1.addComponent(jl);
        
         pg2.addGroup(sq4);

        this.pack();
     JScrollBar vertival  = jScrollPane1.getVerticalScrollBar();
        vertival.setValue(vertival.getMaximum());
        num++;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
        Component[] cmp= backGround.getComponents();
        for (Component component : cmp) {
            
            
            
           
                
                if(component.getName()==("fuck")){
            
                    backGround.remove(component);
                    backGround.revalidate();
                    backGround.repaint();
                    this.pack();
            
            }
            
            
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenueCustomizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenueCustomizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenueCustomizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenueCustomizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenueCustomizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initComponentCustom() {
        
        backGround =new JPanel();

        JLabel TitleLabel = new JLabel();
        
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();

        TitleLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TitleLabel.setText("Munue -");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("Welcome Drink");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("Section 2");

        backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        jScrollPane1.setViewportView(backGround);

        SequentialGroup sq4 = backGroundLayout.createSequentialGroup();
        sq4.addContainerGap();
        sq4.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE);

        SequentialGroup sq3 = backGroundLayout.createSequentialGroup();
        sq3.addContainerGap();
        sq3.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE);

        SequentialGroup sq2 = backGroundLayout.createSequentialGroup();
        sq2.addGap(126, 126, 126);
        sq2.addComponent(TitleLabel, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE);

        pg2 = backGroundLayout.createParallelGroup(GroupLayout.Alignment.LEADING);
        pg2.addGroup(sq2);
        pg2.addGroup(sq3);
        pg2.addGroup(sq4);

        SequentialGroup sq1 = backGroundLayout.createSequentialGroup();
        sq1.addGroup(pg2);
        sq1.addContainerGap(153, Short.MAX_VALUE);

        ParallelGroup pg1 = backGroundLayout.createParallelGroup(GroupLayout.Alignment.LEADING);
        pg1.addGroup(sq1);

        vsq1 = backGroundLayout.createSequentialGroup();

        vsq1.addContainerGap();
        vsq1.addComponent(TitleLabel, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE);
        vsq1.addGap(49, 49, 49);
        vsq1.addComponent(jLabel1);
        vsq1.addGap(94, 94, 94);
        vsq1.addComponent(jLabel2);
        //vsq1.addContainerGap(402, Short.MAX_VALUE);

        ParallelGroup  vpg1 = backGroundLayout.createParallelGroup(GroupLayout.Alignment.LEADING);
        vpg1.addGroup(vsq1);

        backGroundLayout.setHorizontalGroup(pg1);
        backGroundLayout.setVerticalGroup(vpg1);

//        backGroundLayout.setVerticalGroup(
//                backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(backGroundLayout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(49, 49, 49)
//                                .addComponent(jLabel1)
//                                .addGap(94, 94, 94)
//                                .addComponent(jLabel2)
//                                .addContainerGap(402, Short.MAX_VALUE))
//        );
        this.pack();

    }
}
