/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;
import Database.Dbconnection;
import Accountant.AccountantInterface;
import LoanHandling.LoanFrame;
import Cashier.CashierInterfaace;
import Database.GetterSetter;
import Database.ViewReport;
import UserLogging.MainInterface;
import Validation.FormValidate;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Duration;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import org.joda.time.DateTime;
import org.joda.time.Days;
import org.joda.time.LocalDate;
import org.joda.time.Months;
import org.joda.time.ReadablePeriod;
import org.joda.time.format.DateTimeFormat;
/**
 *
 * @author Ravindu
 */
public class ManagerInterface extends javax.swing.JFrame {

    /**
     * Creates new form ManagerInterface
     */
    public ManagerInterface() {
        initComponents();
        try{
        Connection c = Dbconnection.mycon();
        Statement s = c.createStatement();
        ResultSet rs1 = s.executeQuery("Select type,Interest from updatedetails ");
        Accountinfo.setModel(DbUtils.resultSetToTableModel(rs1));
        ResultSet rs2 = s.executeQuery("Select Type,Interest from loaninfo");
        loaninfo.setModel(DbUtils.resultSetToTableModel(rs2));
        }
        catch(Exception e){
            //e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        buttonpanel1 = new javax.swing.JPanel();
        updteLoanInt = new javax.swing.JButton();
        updteAccInt = new javax.swing.JButton();
        ManegerReport = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Mainpanel1 = new javax.swing.JPanel();
        reports = new javax.swing.JPanel();
        Customers = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Update_AccInterest = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldAccIntrst = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newAccIntrst = new javax.swing.JTextField();
        AccIntrst = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Accountinfo = new javax.swing.JTable();
        accinfo = new javax.swing.JTextField();
        Update_loanInterest = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oldLoanIntrst = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newloanIntrst = new javax.swing.JTextField();
        updateloan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        loantype = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        loaninfo = new javax.swing.JTable();
        UpdateAccnts = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastD = new javax.swing.JTextField();
        nextD = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SamShar = new javax.swing.JRadioButton();
        DSK = new javax.swing.JRadioButton();
        MGN = new javax.swing.JRadioButton();
        LOANS = new javax.swing.JRadioButton();
        STAMP = new javax.swing.JRadioButton();
        UpdateLoanAccnts = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lastD1 = new javax.swing.JTextField();
        nextD1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonpanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        updteLoanInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updteLoanInt.setText("Update Loan Interest");
        updteLoanInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updteLoanIntActionPerformed(evt);
            }
        });

        updteAccInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updteAccInt.setText("Update Account Interest");
        updteAccInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updteAccIntActionPerformed(evt);
            }
        });

        ManegerReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ManegerReport.setText("Reports");
        ManegerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManegerReportActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("update Saving Accnts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonpanel1Layout = new javax.swing.GroupLayout(buttonpanel1);
        buttonpanel1.setLayout(buttonpanel1Layout);
        buttonpanel1Layout.setHorizontalGroup(
            buttonpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(buttonpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updteLoanInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManegerReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updteAccInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        buttonpanel1Layout.setVerticalGroup(
            buttonpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(updteAccInt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(updteLoanInt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ManegerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Mainpanel1.setLayout(new java.awt.CardLayout());

        Customers.setText("Customers");
        Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersActionPerformed(evt);
            }
        });

        jButton7.setText("Members");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("Non Members");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Member Savings");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Non member Savings");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Diriya Matha Savings");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportsLayout = new javax.swing.GroupLayout(reports);
        reports.setLayout(reportsLayout);
        reportsLayout.setHorizontalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportsLayout.createSequentialGroup()
                .addComponent(Customers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(60, 60, 60)
                .addComponent(jButton9)
                .addGap(101, 101, 101))
            .addGroup(reportsLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportsLayout.setVerticalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton7)
                    .addComponent(Customers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(82, 82, 82)
                .addComponent(jButton12)
                .addGap(106, 106, 106))
        );

        Mainpanel1.add(reports, "card6");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Account Interest", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Acc Type");

        jLabel2.setText("Interest (Old)");

        oldAccIntrst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldAccIntrstActionPerformed(evt);
            }
        });

        jLabel3.setText("Interest (New)");

        AccIntrst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AccIntrst.setText("Update");
        AccIntrst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccIntrstActionPerformed(evt);
            }
        });

        Accountinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Interest"
            }
        ));
        Accountinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountinfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Accountinfo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        accinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(AccIntrst))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newAccIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(oldAccIntrst, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(accinfo))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(accinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(oldAccIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newAccIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AccIntrst)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Update_AccInterestLayout = new javax.swing.GroupLayout(Update_AccInterest);
        Update_AccInterest.setLayout(Update_AccInterestLayout);
        Update_AccInterestLayout.setHorizontalGroup(
            Update_AccInterestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Update_AccInterestLayout.setVerticalGroup(
            Update_AccInterestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_AccInterestLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Mainpanel1.add(Update_AccInterest, "card2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Loan Interest", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setText("Loan Type");

        jLabel5.setText("Interest (Old)");

        oldLoanIntrst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldLoanIntrstActionPerformed(evt);
            }
        });

        jLabel6.setText("Interest (New)");

        updateloan.setText("Update");
        updateloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateloanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        loantype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loantypeActionPerformed(evt);
            }
        });

        loaninfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Interest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        loaninfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loaninfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(loaninfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(newloanIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateloan)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loantype, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oldLoanIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loantype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oldLoanIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newloanIntrst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(updateloan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Update_loanInterestLayout = new javax.swing.GroupLayout(Update_loanInterest);
        Update_loanInterest.setLayout(Update_loanInterestLayout);
        Update_loanInterestLayout.setHorizontalGroup(
            Update_loanInterestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Update_loanInterestLayout.setVerticalGroup(
            Update_loanInterestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Mainpanel1.add(Update_loanInterest, "card3");

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("update accounts");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("last update");

        jLabel8.setText("next update");

        nextD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextDActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        buttonGroup1.add(SamShar);
        SamShar.setText("Samurdhi & shares");
        SamShar.setEnabled(false);
        SamShar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                SamSharComponentRemoved(evt);
            }
        });
        SamShar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SamSharFocusGained(evt);
            }
        });
        SamShar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamSharActionPerformed(evt);
            }
        });

        buttonGroup1.add(DSK);
        DSK.setText("DSK");
        DSK.setEnabled(false);
        DSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSKActionPerformed(evt);
            }
        });

        buttonGroup1.add(MGN);
        MGN.setText("MGN");
        MGN.setEnabled(false);
        MGN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MGNActionPerformed(evt);
            }
        });

        buttonGroup1.add(LOANS);
        LOANS.setText("LOANS");
        LOANS.setEnabled(false);

        STAMP.setText("STAMP");
        STAMP.setEnabled(false);
        STAMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STAMPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateAccntsLayout = new javax.swing.GroupLayout(UpdateAccnts);
        UpdateAccnts.setLayout(UpdateAccntsLayout);
        UpdateAccntsLayout.setHorizontalGroup(
            UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateAccntsLayout.createSequentialGroup()
                .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateAccntsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(68, 68, 68)
                        .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nextD, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(lastD)))
                    .addGroup(UpdateAccntsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(UpdateAccntsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(UpdateAccntsLayout.createSequentialGroup()
                                    .addComponent(SamShar)
                                    .addGap(18, 18, 18)
                                    .addComponent(DSK)
                                    .addGap(18, 18, 18)
                                    .addComponent(MGN)
                                    .addGap(18, 18, 18)
                                    .addComponent(LOANS))
                                .addComponent(STAMP)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        UpdateAccntsLayout.setVerticalGroup(
            UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateAccntsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SamShar)
                    .addComponent(DSK)
                    .addComponent(MGN)
                    .addComponent(LOANS))
                .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UpdateAccntsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lastD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateAccntsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(STAMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)))
                .addGroup(UpdateAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nextD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Mainpanel1.add(UpdateAccnts, "card4");

        jButton5.setText("search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("update accounts");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setText("last update");

        jLabel10.setText("next update");

        nextD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextD1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout UpdateLoanAccntsLayout = new javax.swing.GroupLayout(UpdateLoanAccnts);
        UpdateLoanAccnts.setLayout(UpdateLoanAccntsLayout);
        UpdateLoanAccntsLayout.setHorizontalGroup(
            UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLoanAccntsLayout.createSequentialGroup()
                .addGroup(UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateLoanAccntsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(68, 68, 68)
                        .addGroup(UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nextD1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(lastD1)))
                    .addGroup(UpdateLoanAccntsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(UpdateLoanAccntsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        UpdateLoanAccntsLayout.setVerticalGroup(
            UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLoanAccntsLayout.createSequentialGroup()
                .addGroup(UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateLoanAccntsLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lastD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLoanAccntsLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)))
                .addGroup(UpdateLoanAccntsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nextD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Mainpanel1.add(UpdateLoanAccnts, "card4");

        dateChooserCombo1.setLocked(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(buttonpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mainpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(buttonpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mainpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updteLoanIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updteLoanIntActionPerformed
        // Move to loan Interest update panel:
        Mainpanel1.removeAll();
        Mainpanel1.add(Update_loanInterest);
        Mainpanel1.repaint();
        Mainpanel1.revalidate();
       
    }//GEN-LAST:event_updteLoanIntActionPerformed

    private void updteAccIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updteAccIntActionPerformed
        // TODO add your handling code here:
        Mainpanel1.removeAll();
        Mainpanel1.add(Update_AccInterest);
        Mainpanel1.repaint();
        Mainpanel1.revalidate();
       
    }//GEN-LAST:event_updteAccIntActionPerformed

    private void ManegerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManegerReportActionPerformed
        Mainpanel1.removeAll();
        Mainpanel1.add(reports);
        Mainpanel1.repaint();
        Mainpanel1.revalidate();
        
    }//GEN-LAST:event_ManegerReportActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Move to the Home Folder
        this.dispose();
        new MainInterface().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AccIntrstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccIntrstActionPerformed
        // Update with new Interest
        if(accinfo.getText().isEmpty())JOptionPane.showMessageDialog(null, "Please select a account from table to continue");
        else{
        
        try{
        Connection c = Dbconnection.mycon();
        Statement s = c.createStatement();
        int x = JOptionPane.showConfirmDialog(rootPane,"Do you really want to update with the new value");
        if(x == 0){
        s.executeUpdate("UPDATE accountinfo SET Interest = '" +newAccIntrst.getText()+ "' where Type = '" + accinfo.getText() + "' ");
        ResultSet rs = s.executeQuery("Select Type,Interest from accountinfo");
        Accountinfo.setModel(DbUtils.resultSetToTableModel(rs));
        }
        else if(x == 1){
            newAccIntrst.setText("");
            accinfo.setText("");
            oldAccIntrst.setText("");
        }
            newAccIntrst.setText("");
           accinfo.setText("");
            oldAccIntrst.setText("");
        }
        catch(Exception e){
            //e.printStackTrace();
        }
        } 
    }//GEN-LAST:event_AccIntrstActionPerformed

    private void AccountinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountinfoMouseClicked
        // Get Details to the text Field
        try{
            Connection c = Dbconnection.mycon();
            Statement s = c.createStatement();
            int row = Accountinfo.getSelectedRow();
            String type = (String) Accountinfo.getValueAt(row, 0);
            String intrst = Accountinfo.getValueAt(row, 1).toString();
            accinfo.setText(type);
            oldAccIntrst.setText(intrst);
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AccountinfoMouseClicked

    private void oldAccIntrstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldAccIntrstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldAccIntrstActionPerformed

    private void accinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accinfoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     FormValidate f1=new FormValidate();
      String accType=""; 
      JTextField fld[]={nextD,lastD};   
    GetterSetter gs1=new GetterSetter();    
    if(!f1.FieldsAreEmpty(fld)){
    
    if(SamShar.isSelected())accType="SamShar";
    else if(DSK.isSelected())accType="DSK";
    else if(MGN.isSelected())accType="MGN";
    else if(LOANS.isSelected())accType="LOANS";
    else if(STAMP.isSelected())accType="STAMP";
             LocalDate lastd=LocalDate.parse(lastD.getText());
             LocalDate nextd=LocalDate.parse(nextD.getText());
             LocalDate now=LocalDate.now();
    
       if(accType=="LOANS")gs1.loanAccUpdater();
       else if(accType=="STAMP")gs1.stampUpdater();
       else      gs1.accountUpdater(accType);
   
    
    try{
    Connection c = Dbconnection.mycon();
            Statement s2=c.createStatement();
            Statement s3=c.createStatement();
            Statement s4=c.createStatement();
            Statement s5=c.createStatement();
     
      LocalDate newNextd=nextd.plusMonths(Months.monthsBetween(lastd, nextd).getMonths());
            
      s2.executeUpdate("update updatedetails SET  LastUpdate = '"+nextD.getText()+"', NextUpdate = '"+newNextd.toString()+"' where type = '"+accType+"'");
            
    
    JOptionPane.showMessageDialog(rootPane, "success");
    }
    
    
    catch(Exception e){e.printStackTrace();
    
    
    }
    
    }
        
     
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        try {
            Connection c = Dbconnection.mycon();
            Statement s = c.createStatement();

            ResultSet rs=s.executeQuery("select * from updatedetails");

           jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        }

        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        String accType = jTable2.getValueAt(row, 0).toString();
        

       lastD.setText(jTable2.getValueAt(row, 2).toString());
       nextD.setText(jTable2.getValueAt(row, 3).toString());
       
            switch (accType){
        
            case "SamShar":SamShar.setSelected(true);
            break;
            case "MGN":MGN.setSelected(true);
            break;
            case "DSK":DSK.setSelected(true);
            break;
            case "LOANS":LOANS.setSelected(true);
            break;
            case "STAMP":STAMP.setSelected(true);
            break;
            
            
            
            
        }
            
            
            
            
            
                     LocalDate lastd=LocalDate.parse(lastD.getText());
          LocalDate nextd=LocalDate.parse(nextD.getText());
          LocalDate now=LocalDate.now();
           //  ReadablePeriod rp=null;
            
            //System.out.println(now.plus(Days.daysBetween(lastd, nextd)));
       // System.out.println(nextd.plusMonths(Months.monthsBetween(lastd, nextd).getMonths()));
            if(now.isBefore(nextd)){
         jButton2.setEnabled(false);
                System.out.println(now+" is before "+nextd);   
     
     }
     else jButton2.setEnabled(true);
   
    }//GEN-LAST:event_jTable2MouseClicked

    private void SamSharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamSharActionPerformed
  
        

    
             
    }//GEN-LAST:event_SamSharActionPerformed

    private void DSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSKActionPerformed

    }//GEN-LAST:event_DSKActionPerformed

    private void MGNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MGNActionPerformed

    }//GEN-LAST:event_MGNActionPerformed

    private void nextDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      Mainpanel1.removeAll();
        Mainpanel1.add(UpdateAccnts);
        Mainpanel1.repaint();
        Mainpanel1.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SamSharComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_SamSharComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_SamSharComponentRemoved

    private void SamSharFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SamSharFocusGained

    }//GEN-LAST:event_SamSharFocusGained

    private void loaninfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaninfoMouseClicked
        // Get Selected row to the text fields
        int row = loaninfo.getSelectedRow();
        String type = (String) loaninfo.getValueAt(row, 0);
        String intrst = loaninfo.getValueAt(row, 1).toString();
        loantype.setText(type);
        oldLoanIntrst.setText(intrst);
    }//GEN-LAST:event_loaninfoMouseClicked

    private void loantypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loantypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loantypeActionPerformed

    private void updateloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateloanActionPerformed

        String loanType="";

        if(loantype.getText().isEmpty())JOptionPane.showMessageDialog(null, "Please select a account from table to continue");
        else{
            try{
                Connection c = Dbconnection.mycon();
                Statement s = c.createStatement();
                int x = JOptionPane.showConfirmDialog(rootPane,"Do you really want to update with the new value");
                if(x == 0){
                    s.executeUpdate("UPDATE loaninfo SET Interest = '" +newloanIntrst.getText()+ "' where Type = '" +loantype.getText()+ "' ");
                    ResultSet rs = s.executeQuery("Select Type,Interest from loaninfo");
                    loaninfo.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else if(x == 1){
                    newloanIntrst.setText("");
                    loantype.setText("");
                    oldLoanIntrst.setText("");
                }
                newloanIntrst.setText("");
                loantype.setText("");
                oldLoanIntrst.setText("");
            }
            catch(Exception e){
                //e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateloanActionPerformed

    private void oldLoanIntrstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldLoanIntrstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldLoanIntrstActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              try {
            Connection c = Dbconnection.mycon();
            Statement s = c.createStatement();

            ResultSet rs=s.executeQuery("select * from updatedetails");

           jTable3.setModel(DbUtils.resultSetToTableModel(rs));

        }

        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nextD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextD1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
    int row = jTable2.getSelectedRow();
        String accType = jTable2.getValueAt(row, 0).toString();
        

       lastD.setText(jTable2.getValueAt(row, 2).toString());
       nextD.setText(jTable2.getValueAt(row, 3).toString());
       
            switch (accType){
        
            case "SamShar":SamShar.setSelected(true);
            break;
            case "MGN":MGN.setSelected(true);
            break;
            case "DSK":DSK.setSelected(true);
            break;
            
            
            
            
            
            
        }
            
            
            
            
            
                     LocalDate lastd=LocalDate.parse(lastD.getText());
          LocalDate nextd=LocalDate.parse(nextD.getText());
          LocalDate now=LocalDate.now();
           //  ReadablePeriod rp=null;
            
            //System.out.println(now.plus(Days.daysBetween(lastd, nextd)));
       // System.out.println(nextd.plusMonths(Months.monthsBetween(lastd, nextd).getMonths()));
            if(now.isBefore(nextd)){
         jButton2.setEnabled(false);
                System.out.println(now+" is before "+nextd);   
     
     }
     else jButton2.setEnabled(true);
   
    }//GEN-LAST:event_jTable3MouseClicked

    private void STAMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STAMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STAMPActionPerformed

    private void CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersActionPerformed
       ViewReport r=new ViewReport("F:\\JavaApplication20\\src\\Database\\report1.jasper");
       r.setVisible(true);
    }//GEN-LAST:event_CustomersActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      ViewReport r=new ViewReport("F:\\JavaApplication20\\src\\Manager\\members.jasper");
       r.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 ViewReport r=new ViewReport("F:\\JavaApplication20\\src\\Manager\\DiriyaMatha.jasper");
       r.setVisible(true);        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ViewReport r=new ViewReport("F:\\JavaApplication20\\src\\Manager\\nonMem.jasper");
       r.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       ViewReport r=new ViewReport("F:\\JavaApplication20\\src\\Manager\\memSavings.jasper");
       r.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       ViewReport r=new ViewReport("F:\\JavaApplication20\\src\\Manager\\nonMemSavngs.jasper");
       r.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccIntrst;
    private javax.swing.JTable Accountinfo;
    private javax.swing.JButton Customers;
    private javax.swing.JRadioButton DSK;
    private javax.swing.JRadioButton LOANS;
    private javax.swing.JRadioButton MGN;
    private javax.swing.JPanel Mainpanel1;
    private javax.swing.JButton ManegerReport;
    private javax.swing.JRadioButton STAMP;
    private javax.swing.JRadioButton SamShar;
    private javax.swing.JPanel UpdateAccnts;
    private javax.swing.JPanel UpdateLoanAccnts;
    private javax.swing.JPanel Update_AccInterest;
    private javax.swing.JPanel Update_loanInterest;
    private javax.swing.JTextField accinfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel buttonpanel1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField lastD;
    private javax.swing.JTextField lastD1;
    private javax.swing.JTable loaninfo;
    private javax.swing.JTextField loantype;
    private javax.swing.JTextField newAccIntrst;
    private javax.swing.JTextField newloanIntrst;
    private javax.swing.JTextField nextD;
    private javax.swing.JTextField nextD1;
    private javax.swing.JTextField oldAccIntrst;
    private javax.swing.JTextField oldLoanIntrst;
    private javax.swing.JPanel reports;
    private javax.swing.JButton updateloan;
    private javax.swing.JButton updteAccInt;
    private javax.swing.JButton updteLoanInt;
    // End of variables declaration//GEN-END:variables
}
