/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package canteen;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.time.*;
import javax.swing.JFrame;
/**
 *
 * @author kiwa
 */
public class HOME2Customer extends javax.swing.JFrame {
  private String Cust_ID="";
  String Cust_name;
  
            Connection c; //= new BSDB().con();
           
            Statement st;//=c.createStatement();
            ResultSet r1;//=st.executeQuery("select Cust_ID from cust_login where username='"+username.getText()+"'");
            
            
    /**
     * Creates new form HOME2Customer
     */
    public HOME2Customer() {
        
        initComponents();
        //searchDetails();
       fillFoodName();
       
    }
    
    public void getCustID(String id){
      this.Cust_ID=id;
      searchDetails();
       try{
       c= new BSDB().con();
       st=c.createStatement();
       r1=st.executeQuery("select cus_name from customer where Cust_ID = '"+Cust_ID+"'");
       if(r1.next()){Cust_name=r1.getString("cus_name");}
       }
       catch(Exception e){
           System.out.println(e); 
           
       }
       
       
       custName.setText(Cust_name);
    }
    
    
    public void fillFoodName(){
         String foodname = " ";
        try {
            Connection c = new BSDB().con();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM food_item";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                foodname = rs.getString("food_name");
                jFoodItem.addItem(foodname);
                
            } 
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }

    }

    
    
    
    public void searchDetails() {

        try {
            Connection c = new BSDB().con();
            Statement st = c.createStatement();

         
            
            String tbl = "select * from orders where Order_ID IN (SELECT Order_ID FROM cust_orders where Cust_ID IN('"+Cust_ID+"'))";
            ResultSet rs = st.executeQuery(tbl);
            cusOrders.setModel(DbUtils.resultSetToTableModel(rs));
            

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cusOrders = new javax.swing.JTable();
        jFoodItem = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        jamount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        junitPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        date1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cusOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Quantity", "Price", "Date"
            }
        ));
        cusOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cusOrders);

        jFoodItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFoodItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jFoodItemItemStateChanged(evt);
            }
        });
        jFoodItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodItemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Welcome ");

        custName.setText("custName");

        jamount.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jamountCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jamountInputMethodTextChanged(evt);
            }
        });
        jamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamountActionPerformed(evt);
            }
        });
        jamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jamountKeyTyped(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setText("food name");

        jLabel4.setText("quantity");

        jLabel5.setText("date");

        jLabel6.setText("descrition");

        updateButton.setText("add order");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("unit price");

        jLabel9.setText("total price");

        jButton1.setText("change username password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 118, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(243, 243, 243)
                        .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jamount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(junitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFoodItem, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(custName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFoodItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(junitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateButton)
                            .addComponent(jButton1))
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      String currentOrderID;
    private void cusOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusOrdersMouseClicked
        /* try{
            Connection c1;
            c1= new BSDB().con();
            Statement st = c1.createStatement();
           // String sql = "SELECT * FROM supplier";
           // ResultSet rs = st.executeQuery(sql);
            
            int row=cusOrders.getSelectedRow();
            String Table_Click=(cusOrders.getModel().getValueAt(row,0).toString());
            String sql="Select * from orders where Order_ID='"+ Table_Click+"'";
            //getting food name
            
           // String supName="select Sup_name from supplier where Sup_ID=(select Sup_ID from sup_orders where Order_ID='"+Table_Click+"')";
           
            String foodName="select Food_name from food_item where Food_ID=(select Food_ID from orders where Order_ID ='"+Table_Click+"')"; 
           // jComboBox2.setSelectedItem( jComboBox1.getSelectedItem());
            //st=c.prepareStatement(Sql);
          //pst2=c.prepareStatement(foodName);
            //jComboBox3.setSelected
       
        ResultSet rs1=st.executeQuery(sql);
         while(rs1.next()){
         // text4.setText(rs1.getString(0));
               //setting food name for selected row
                st=c1.prepareStatement(foodName);
                ResultSet rs2=st.executeQuery(foodName);
                if(rs2.next()){jFoodItem.setSelectedItem(rs2.getString("Food_name"));}
               //String add1=rs.getString("SupName");
         //       jComboBox2.addItem(add1);
                Date add2=rs1.getDate("date");
               date1.setDate(add2);
              // String add3=pst2.executeQuery(foodName).getNString("Food_name");
                //text3.setText(add3);
               
                String add4=rs1.getString("amount");
                jamount.setText(add4);
                
                //updating totalprice label
                int units,unitprice;
                String total;
                units=Integer.parseInt(add4);
                unitprice=Integer.parseInt(jamount.getText());
                total=String.valueOf(units*unitprice);
                jLabel10.setText(total);
                
                
               // String add5=rs1.getString("unit_price");
                //text5.setText(add5);
                 //text4.setText("dvdfdg");
                String add6=rs1.getString("description");
                jTextArea1.setText(add6);
                 currentOrderID=rs1.getString("Order_ID");
         }   
            
            
            
        }
        catch(Exception e){
            System.out.println(e);
             JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_cusOrdersMouseClicked

    private void jamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamountActionPerformed
      
        int amount=Integer.parseInt(jamount.getText());
        int  unitprice=Integer.parseInt(junitPrice.getText()); 
        String total=String.valueOf(amount*unitprice);
                
        jLabel10.setText(total);
        
        
        
    }//GEN-LAST:event_jamountActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try{
          Connection c1;
            c1= new BSDB().con();
            Statement pst = c1.createStatement();
            
            
            
          String foodname= jFoodItem.getSelectedItem().toString();
           String v2= date1.getDateTimePermissive().toString();
          String v3="";
          //String v4= text4.getText();
          String quant= jamount.getText();
          String desc= jTextArea1.getText();
          String datecompiler = v2;//String.format("%1$tY-%1$tm-%1$td", v2);
          
          
          
          //getting supplier id
         //String supName="select Sup_ID from supplier where sup_name='"+v1+"'";
          //ResultSet rs=pst.executeQuery(supName);
          //(rs.next()){v1=rs.getString("Sup_ID");}
          
          //taking food_ID
          String foodName="select Food_ID from food_item where Food_name='"+foodname+"'";
          ResultSet rs=pst.executeQuery(foodName);
          while(rs.next()){v3=rs.getString("Food_ID");}
          
          //updating order table
          
          int check=JOptionPane.showConfirmDialog(null," Confirm order? ","Order Confirmation",JOptionPane.YES_NO_OPTION); 
          
          if(check==JOptionPane.YES_OPTION){
          
            String neworder ="insert into orders(date,amount,unit_price,description,Food_ID)  values('"+datecompiler+"','"+ quant+"','"+junitPrice.getText()+"','"+desc+"','"+v3+"')"; 
           pst=c1.prepareStatement(neworder);
           pst.executeUpdate(neworder);
          
           //updating cust_order table
           pst=c1.createStatement();
           Statement s2=c1.createStatement();
             ResultSet r1=pst.executeQuery("SELECT * FROM orders order by Order_ID desc limit 1");
            while(r1.next()){
             s2.executeUpdate("insert into cust_orders values('"+Cust_ID+"','"+r1.getString("Order_ID")+"')");
             JOptionPane.showMessageDialog(null, "updated");
             searchDetails();
            }
          
          }
          
          
         
         
          
          
          // pst=c.prepareStatement(Sql);
           
          // pst.executeUpdate(Sql);
            
           
      }
      catch(Exception e){
          System.out.println(e);
           JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jamountInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jamountInputMethodTextChanged
        // TODO add your handling code here:
        
      
        
        
        
        
        
    }//GEN-LAST:event_jamountInputMethodTextChanged

    private void jamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jamountKeyTyped

    private void jamountCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jamountCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jamountCaretPositionChanged

    private void jFoodItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFoodItemActionPerformed

    private void jFoodItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jFoodItemItemStateChanged
          String currentUnit= jFoodItem.getSelectedItem().toString();
      String sql="select unit_price from food_item where Food_name='"+currentUnit+"'";
      try{
      Connection c1;
            c1= new BSDB().con();
            Statement pst = c1.createStatement();
            ResultSet rs=pst.executeQuery(sql);
            while(rs.next()){junitPrice.setText(rs.getString("unit_price"));}
            
            
            
      }
      catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jFoodItemItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CusPasswordChange c1=new CusPasswordChange();
        c1.setVisible(true);
        
        c1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        c1.getCusID(Cust_ID);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME2Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME2Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME2Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME2Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME2Customer().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cusOrders;
    private javax.swing.JLabel custName;
    private com.github.lgooddatepicker.components.DateTimePicker date1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jFoodItem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jamount;
    private javax.swing.JLabel junitPrice;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
