/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package canteen;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kiwa
 */
public class Sup_Order extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Sup_Order() {
        initComponents();
        fillFoodName();
         fillsupName();
    }
    
    public void fillFoodName(){
         String foodname = " ";
        try {
            Connection c = new BSDB().con();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM food_item";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                foodname = rs.getString("Food_name");
                food.addItem(foodname);
                
            } 
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    public void fillsupName(){
         String supname="" ;
        try {
            Connection c = new BSDB().con();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM supplier";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                supname = rs.getString("Sup_name");
                SupName.addItem(supname);
                
            }
            
            
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Quntity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SupName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UnitPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descript = new javax.swing.JTextArea();
        food = new javax.swing.JComboBox();
        jDate1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quntity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Quntity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuntityKeyTyped(evt);
            }
        });
        getContentPane().add(Quntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 26));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Unit price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Food");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 26));

        SupName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupNameActionPerformed(evt);
            }
        });
        getContentPane().add(SupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quntity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Supplier Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 26));

        UnitPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UnitPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UnitPriceKeyTyped(evt);
            }
        });
        getContentPane().add(UnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Description");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 26));

        descript.setColumns(20);
        descript.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        descript.setRows(5);
        jScrollPane1.setViewportView(descript);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, -1));

        food.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        getContentPane().add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, 30));
        getContentPane().add(jDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen/B1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Date date = jDate1.getDate();
            String datecompiler = String.format("%1$tY-%1$tm-%1$td", date);
            Connection c = new BSDB().con();
            Statement s = c.createStatement();
            Statement s2 = c.createStatement();
            //ResultSet numT=s.executeQuery("select max(ID) from orders;");
            
            //updating orders table
            ResultSet rs=s.executeQuery("select Food_ID from food_item where food_name='"+food.getSelectedItem()+"'");
            String foodID="";
            while(rs.next()){foodID=rs.getString("Food_ID");}
            s.executeUpdate("insert into orders(date,amount,unit_price,description,Food_ID) values('"  + datecompiler + "','" +  Quntity.getText()+ "','" + UnitPrice.getText()+ "','" + descript.getText()+"','" + foodID +"')");
            
            //taking sup_ID from sup_name
            ResultSet rs1=s.executeQuery("select Sup_ID from supplier where sup_name='"+SupName.getSelectedItem()+"'");
            String supID="";
             while(rs1.next()){supID=rs1.getString("Sup_ID");}
            //System.out.println(supID);
            
            //taking order_ID for the order
            ResultSet r1=s.executeQuery("SELECT * FROM orders order by Order_ID desc limit 1");
                   // s2.executeQuery("select Sup_ID from supplier where Sup_name='"+Name.getText()+"' and Address ='"+Address.getText()+"'");
            String orderID="";
            while(r1.next()){orderID=r1.getString("Order_ID");}
             
              
            
            //updating sup_order table
            s.executeUpdate("insert into sup_orders values('"+supID+"','"+orderID+"')");
            
            //incrementing food quantity
            s.executeUpdate("update food_item set stock_amount= stock_amount + '"+Quntity.getText()+"' where Food_ID='"+foodID+"'");
            
            JOptionPane.showMessageDialog(this, "Save Completed");
           // s.executeUpdate("update food_item set stock_amount=(select stock_amount from food_item where Food_ID='"+foodID+"')
            
            this.Quntity.setText(null);
            this.UnitPrice.setText(null);
            this.descript.setText(null);
            
        } catch (Exception e) {
           
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed

    private void SupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupNameActionPerformed
        // TODO add your handling code here:
        
       
        
    
    }//GEN-LAST:event_SupNameActionPerformed

    private void UnitPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnitPriceKeyTyped
        // TODO add your handling code here:
         char n=evt.getKeyChar();
         if(!(Character.isDigit(n)|| n==KeyEvent.VK_BACK_SPACE || n==KeyEvent.VK_DELETE)){
               getToolkit().beep();
            evt.consume();
         }
        
    }//GEN-LAST:event_UnitPriceKeyTyped

    private void QuntityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuntityKeyTyped
        // TODO add your handling code here:
         char n=evt.getKeyChar();
         if(!(Character.isDigit(n)|| n==KeyEvent.VK_BACK_SPACE || n==KeyEvent.VK_DELETE)){
               getToolkit().beep();
            evt.consume();
         }
    }//GEN-LAST:event_QuntityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sup_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sup_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sup_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sup_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sup_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Quntity;
    private javax.swing.JComboBox SupName;
    private javax.swing.JTextField UnitPrice;
    private javax.swing.JTextArea descript;
    private javax.swing.JComboBox food;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
